### ISSUE TITLE
compilation error due to missing dependency (glfw3)

### ISSUE THREAD

**Issue by user062** [PikoStudios/Muzzle#20]
When compiling under Linux 

![image](https://user-images.githubusercontent.com/48716714/136674209-34ec6c6d-1d54-498e-a194-3724ddc973bc.png)

I think glfw3.h should either be bundled (which creates another dependency on the maintainers) or it should be symlinked from the system-wide installation (which would need to be distro agnostic), or it should just be assumed that it's installed and available system-wide.

I think the solution is the just assume it to be system-wide installed.

**Comment by OkiStuff** [comment]
I agree with it being assumed to be installed system-wide. Only weird part is that if you have the submodule installed, glfw3.h should be there without even compiling GFLW3, anyways I'll add a macro called `MZ_DEPS_USE_GLOBAL` that tries to include the system-wide headers.

**Comment by user062** [comment]
actually, i just realized i was being so stupid, because i didn't notice the sub-module until now.

it works now that i did a `git submodule update --init --recursive`

sorry for the ignorance on my part.
