### ISSUE TITLE
Switching to GNU GPL v3.0

### ISSUE THREAD

**Issue by OkiStuff** [PikoStudios/Muzzle#22]
https://choosealicense.com/licenses/gpl-3.0/#

The GNU GPL v3.0 looks like a very nice alternative to MIT. What do you guys think?

**Comment by abdoreact** [comment]
It seems good, but isn't MIT the exact same thing.

**Comment by OkiStuff** [comment]
not really
just read GPL3 and MIT side by side.. there are differences
