### ISSUE TITLE
Issue With Rendering

### ISSUE THREAD

**Issue by tacotacoenchilada** [PikoStudios/Muzzle#26]
The Rendering System For Drawing A Cube Is Broken. I tried to Fix it by editing the source code and it worked but uhmm yeah

**Comment by OkiStuff** [comment]
did you try to use the modern renderer?

**Comment by OkiStuff** [comment]
if you did, thats the problem

**Comment by tacotacoenchilada** [comment]
stfu

**Comment by tacotacoenchilada** [comment]
wait actually

**Comment by tacotacoenchilada** [comment]
no
